### ISSUE TITLE
localhost peer and aws peer

### ISSUE THREAD

**Issue by Amrosx** [SyntropyNet/syntropy-agent#3]
I am trying to connect tow peers between localhost and aws ubuntu instance. Why not connected and what is the error? 
poket lost 100%  and no error information?
is there a router setting I should do ?

![image](https://user-images.githubusercontent.com/37171239/127739966-5c17ce80-d5cc-4eb9-872b-e127a8ed9c93.png)

**Comment by Omranic** [comment]
Thank you @Amrosx for your question.

However to help you best I'd suggest you [open a ticket](https://syntropy.atlassian.net/servicedesk/customer/portals) and the team will take care of it, as this is not related to this development repo.

Once you create a ticket there, the team will followup with you on that ticket. Also, make sure you check our [Documentation platform](https://docs.syntropystack.com/docs). We are constantly updating and improving it, so you will find most of the answers to your questions there, as well.
